version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pt-admin-service
    ports:
      - "8081:8081"
    environment:
      # Spring profile & server
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: "8081"
      SERVER_CTX_PATH: /

      # JDBC cho Spring Boot (KHÔNG dùng dấu nháy)
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@(DESCRIPTION=(TRANSPORT_CONNECT_TIMEOUT=5)(CONNECT_TIMEOUT=5)(RETRY_DELAY=10)(RETRY_COUNT=2)(FAILOVER=ON)(LOAD_BALANCE=off)(ADDRESS=(PROTOCOL=TCP)(HOST=34.71.97.204)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=FREEPDB1)))
      SPRING_DATASOURCE_USERNAME: ADMIN_OWNER
      SPRING_DATASOURCE_PASSWORD: Abc@123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      # (tuỳ) Tắt tạo schema tự động nếu DB đã có:
      SPRING_JPA_HIBERNATE_DDL_AUTO: none

      # Mail
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: "587"
      MAIL_USERNAME: it.vissoft@gmail.com
      MAIL_PASSWORD: puba sxjs aijm idas
      MAIL_PROTOCOL: smtp

      # Redis
      REDIS_URL: 10.10.151.188:7000,10.10.151.188:7001,10.10.151.188:7002,10.10.151.188:7003,10.10.151.188:7004,10.10.151.188:7005
      REDIS_PASSWORD: "123456"

      # MinIO
      MINIO_URL: https://api-minio-vnsky.vissoft.vn
      MINIO_ACCESS_KEY: GtdbB7RKwZI7hjLnEefY
      MINIO_SECRET_KEY: 64Uv47y6dt5n3kkxvXx6KNdiLuyAm2E2AVgrvW2S
      MINIO_PUBLIC_BUCKET: bcss-public-dev
      MINIO_BUCKET_PRIVATE: bcss-private-dev

      # Kafka
      MQ_HOST: kafka-vnsky.vissoft.vn
      MQ_PORT: "8084"
      MQ_GROUP_ID: admin-service-local
      JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required username="vnsky" password="Vn5ky0903";

      # RSA keys (dùng block scalar | thay vì chuỗi có dấu nháy)
      RSA_PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAs47Jzq99kD3VDGu/lUp94JZAhXNHot/31s5bP0bm/skOy7s5kd9JjL7yuhfzldaUg/7lUBxk4TrCOyQ0cOGd04q0SyJLaAbkz77JDAA7OUePDU0mWGVNdULP+4ofdILiKjzqoecGgO687ejWO9EmfWoQt34iHbtaBkChB4qv1lGyhqzEwma5aOFaMWZHGc1PgNCuzJ67wL3DE+2lqoNwiMXlB/WXy7r1sfHPw5SImThi44YkJYX2T6PNxJHCg76/nvWsVLvsC2XXDfRg3icp6Q+9YQHuwAYrLS3l7mw8JYVqNnuoAHUc5BWhVCCdndi4LDaP+VJ0GFyddsqVSD4mAxRhhrZnpmkSdZznNhvu3YbQQ9EBq7Eohsw+8JEAZ+LJpLzTkRAjA3f7aSS5Xoj4qdFX2/oJoT4BCvWGr/sHUfJ2vhl1MfmSpca25N+PJ2inv+rsmDJ2OW4lnKprH5Or2y8eWWQJ14Av1CHTEjXJUMqK6gscLsyBg+H3e7fgiNMmW24pyUcOXu7eWdECZdbD9603yMwNP7J0rpvSBthmPeLqzHlr3YOOilfQoIhgDPXlSZT8EFMxtGjo2hNO/+ixpZR0VbJ+vmCUQLeetRCZNB6GPCBTTU5TjjWp2Ti/3+WVeX8lONKJo3prx8+1IsQfo0qdgMK268Qx/BbSU41Cw20CAwEAAQ==
        -----END PUBLIC KEY-----
      RSA_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        (…nguyên nội dung private key của bạn…)
        -----END RSA PRIVATE KEY-----

      # Google OAuth (khuyên chuyển sang file/secrets)
      GOOGLE_CLOUD_API_KEY: |
        {"web":{"client_id":"936937878730-fcvt1hpp5rb0a4gpqrmqhsl2q87cmvad.apps.googleusercontent.com","project_id":"vis-app-381716","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"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","redirect_uris":["http://localhost:8080/login/oauth2/code/google"],"javascript_origins":["http://localhost:8080"]}}

      # URLs khác
      INTERNAL_WEB_URL: https://bcss-vnsky.vissoft.vn
      PARTNER_WEB_URL: https://partner.bcss-vnsky.vissoft.vn
      DOMAIN_SALE: https://hvn-api.vissoft.vn/hvn-sale-service