services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vnsky/spring-app:latest
    container_name: vnsky-spring-app
    env_file:
      - .env
    ports:
      - "${APP_PORT_HOST:-8081}:8081"
    restart: unless-stopped