INSERT INTO CLIENT (ID, CODE, NAME, CONTACT_NAME, CONTACT_POSITION, CONTACT_PHONE, CONTACT_EMAIL,
                                PERMANENT_ADDRESS, PERMANENT_PROVINCE_ID, PERMANENT_DISTRICT_ID, PERMANENT_WARD_ID,
                                TAX_CODE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, STATUS)
VALUES ('000000000000', 'VNSKY', 'VNSKY', 'Công ty TNHH Dịch vụ Số DIGILIFE Việt Nam', null,
        '0945622922', null, 'Tầng 11 -12, Số 36 Hoàng Cầu', 1, 6, 190, '0108755246', 'system',
        TIMESTAMP '2024-09-09 13:12:36', 'system', TIMESTAMP '2024-09-09 13:12:38', 1);

INSERT INTO "USER" (ID, USERNAME, PASSWORD, FULLNAME, DATE_OF_BIRTH, POSITION_TITLE, STATUS, TYPE, ID_CARD_NO, PHONE_NUMBER, LOGIN_FAILED_COUNT, PASSWORD_EXPIRE_TIME, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, GENDER, CLIENT_ID)
VALUES ('01J7AQ07XY0WXQV1DWS0VQJ0GD', 'it.vissoft@gmail.com', '$2a$04$JymRX3i64HZPDOqgeQ9ysOUk6./1SPbdmkE69SpHYta5.KP4FdioG', 'VNSKY Admin', TIMESTAMP '2024-01-01 13:17:38', null, 1, 'owner', null, null, 0, null, 'system', TIMESTAMP '2024-09-09 13:19:06.000000', 'system', TIMESTAMP '2024-09-09 13:19:04.000000', 1, '000000000000');


INSERT INTO DEPARTMENT (ID, NAME, STATUS, CODE) VALUES (1, 'P. Vận hành kỹ thuật', 1, 'TECHNICAL_OPERATION');
INSERT INTO DEPARTMENT (ID, NAME, STATUS, CODE) VALUES (2, 'Phòng CSKH', 1, 'CUSTOMER_CARE');
INSERT INTO DEPARTMENT (ID, NAME, STATUS, CODE) VALUES (3, 'PKD VT truyền thống', 1, 'OFFLINE_TELECOM_SALE');
INSERT INTO DEPARTMENT (ID, NAME, STATUS, CODE) VALUES (4, 'PKD VT trực tuyến', 1, 'ONLINE_TELECOM_SALE');
INSERT INTO DEPARTMENT (ID, NAME, STATUS, CODE) VALUES (5, 'Marketing ', 1, 'MARKETING');
INSERT INTO DEPARTMENT (ID, NAME, STATUS, CODE) VALUES (6, 'P. SPCS', 1, 'POLICY_AND_PRODUCT');
INSERT INTO DEPARTMENT (ID, NAME, STATUS, CODE) VALUES (7, 'P. Phát triển phần mềm', 1, 'SOFTWARE_DEVELOPMENT');
INSERT INTO DEPARTMENT (ID, NAME, STATUS, CODE) VALUES (8, 'P. Tài chính kế toán', 1, 'FINANCE_AND_ACCOUNTING');
INSERT INTO DEPARTMENT (ID, NAME, STATUS, CODE) VALUES (9, 'P. Tổ chức hành chính', 1, 'ADMINISTRATIVE');

-- 3rd party client
INSERT INTO CLIENT (ID, CODE, NAME, CONTACT_NAME, CONTACT_POSITION, CONTACT_PHONE, CONTACT_EMAIL,
                    PERMANENT_ADDRESS, PERMANENT_PROVINCE_ID, PERMANENT_DISTRICT_ID, PERMANENT_WARD_ID,
                    TAX_CODE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, STATUS)
VALUES ('3RD000000000', null, 'VNSKY PRO', null, null,
        null, null, null, null, null, null, null, 'system',
        TIMESTAMP '2024-11-26 13:12:36', 'system', TIMESTAMP '2024-11-26 13:12:38', 1);

--  vnsky_pro@mailinator.com / VnskyPr0@2024
INSERT INTO "USER" (ID, USERNAME, EMAIL, PASSWORD, FULLNAME, DATE_OF_BIRTH, POSITION_TITLE, STATUS, TYPE, ID_CARD_NO, PHONE_NUMBER, LOGIN_FAILED_COUNT, PASSWORD_EXPIRE_TIME, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, GENDER, CLIENT_ID)
VALUES ('01JDKBPTM0HYBPYX55V5CZ7X9V', 'vnsky_pro@mailinator.com', 'vnsky_pro@mailinator.com', '$2a$04$QIIwMHCthsACnxef5ZlWcetQ4HWKUPmBg6dV1LzAZf.FGrpvqHyG.', 'VNSKY Admin', TIMESTAMP '2024-01-01 13:17:38', null, 1, 'owner', null, null, 0, null, 'system', TIMESTAMP '2024-11-26 13:19:06.000000', 'system', TIMESTAMP '2024-11-26 13:19:04.000000', 1, '3RD000000000');
