alter table SALE_OWNER.STOCK_ISDN
    add TRANSFER_TYPE NUMBER(1)
/

comment on column SALE_OWNER.STOCK_ISDN.TRANSFER_TYPE is 'Loại điều chuyển'
/



alter table ADMIN_OWNER.OBJECT_ACTION
    add ID CHAR(26)
/

alter table ADMIN_OWNER.OBJECT_ACTION
    add NAME VARCHAR2(100)
/

alter table ADMIN_OWNER.OBJECT_ACTION
    add STATUS NUMBER(1) default 1
/

delete from ADMIN_OWNER.OBJECT_ACTION where ACTION_ID not in (select ID from ACTION);
delete from ADMIN_OWNER.OBJECT_ACTION where OBJECT_ID not in (select ID from OBJECT);


alter table ADMIN_OWNER.OBJECT_ACTION
    add constraint OBJECT_ACTION_OBJECT_ID_FK
        foreign key (OBJECT_ID) references OBJECT
/

alter table ADMIN_OWNER.OBJECT_ACTION
    add constraint OBJECT_ACTION___FK
        foreign key (ACTION_ID) references ACTION
/


alter table ADMIN_OWNER.OBJECT_ACTION
    modify ID not null
/

alter table ADMIN_OWNER.OBJECT_ACTION
    modify STATUS not null
/

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'SALE_MANAGEMENT'
WHERE t.ID LIKE '01JD9J5H8XT73661QWHT819TAM' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'PROMOTIONAL_PROGRAM'
WHERE t.ID LIKE '01JDPE71HT3CFAVPBR8QTRTHDR' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'KIT_CRAFT_IN_BATCH'
WHERE t.ID LIKE '01JEN83VVZKQRWPS6DZVP0CACJ' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'PROMOTION_CATALOG'
WHERE t.ID LIKE '01JFH57TFMW34KGZWWRZBDNZKT' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'KIT_CRAFT_SINGLE'
WHERE t.ID LIKE '01JEA8G68GVGCT9N9KWKKD3Q4M' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'KIT_CRAFT_IN_BATCH'
WHERE t.ID LIKE '01JEA8HW95HD71R885QDR55QN9' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'AGENCY_REPORT'
WHERE t.ID LIKE '01JH54W0W09JRG6PPQG22B347X' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'CHANGE_SIM_REPORT'
WHERE t.ID LIKE '01JH54ZCBKC2K2WX2KY4QC196M' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'POST_REVIEW_REPORT'
WHERE t.ID LIKE '01JH54XHSHGQ89YKSPFZB65XR9' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'PACKAGE_RETAIL'
WHERE t.ID LIKE '01JFJ3PSR416KEE6RJAAV3KN54' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'PRE_REVIEW_REPORT'
WHERE t.ID LIKE '01JH54SYV534GTD60RHAEAP95Q' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'CRITERIA_REPORT'
WHERE t.ID LIKE '01JH54YE6G8CHV8TEGZDFGQ6VM' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'ONLINE_ORDER_PICK_AT_STORE'
WHERE t.ID LIKE '01JEZSBWCF1YWQA81JS0TNKPA2' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'SUBSCRIBER_TOPUP'
WHERE t.ID LIKE '01JET9YHS872GKJEJ75H5B6P5W' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'ACCOUNTING_PERIOD_LOCK'
WHERE t.ID LIKE '01JDRF7AANQH4YEM1XRS7QQD4S' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'PARAMETER_CONFIG'
WHERE t.ID LIKE '01JDRV4EM5FPZPE6R37W16P6P5' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'SUBSCRIBER_ACTIVATION_REPORT'
WHERE t.ID LIKE '01JH54N8XX9EH3Y9E1QXTXV54C' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT t
SET t.CODE = 'PACKAGE_WHOLE_SALE'
WHERE t.ID LIKE '01JFJ3NT6KX8V688RDY8DJWN9C' ESCAPE '#';

UPDATE ADMIN_OWNER.OBJECT_ACTION SET ACTION_ID = '01JH70P8231ZFZE2AWV4PPF7RJ' WHERE ACTION_ID = '01GWQ5g7b1N940o2p7YBQXQAJ ';
UPDATE ADMIN_OWNER.OBJECT_ACTION SET ACTION_ID = '01JH70PE3282KVM4TVYJ8KXQ9W' WHERE ACTION_ID = '01GWQ5g7b1N940o2p7YBQXQZZ ';
UPDATE ADMIN_OWNER.OBJECT_ACTION SET ACTION_ID = '01JH70PH9A0N09HZGGF8BP2ZSX' WHERE ACTION_ID = 'AFABB17D8DFC46C5BD4C66F6A ';
UPDATE ADMIN_OWNER.ROLE_OBJECT_ACTION SET ACTION_ID = '01JH70P8231ZFZE2AWV4PPF7RJ' WHERE ACTION_ID = '01GWQ5g7b1N940o2p7YBQXQAJ ';
UPDATE ADMIN_OWNER.ROLE_OBJECT_ACTION SET ACTION_ID = '01JH70PE3282KVM4TVYJ8KXQ9W' WHERE ACTION_ID = '01GWQ5g7b1N940o2p7YBQXQZZ ';
UPDATE ADMIN_OWNER.ROLE_OBJECT_ACTION SET ACTION_ID = '01JH70PH9A0N09HZGGF8BP2ZSX' WHERE ACTION_ID = 'AFABB17D8DFC46C5BD4C66F6A ';
UPDATE ADMIN_OWNER.ACTION t
SET t.CODE = 'CONFIRM'
WHERE t.ID LIKE '01JH70P8231ZFZE2AWV4PPF7RJ' ESCAPE '#';

UPDATE ADMIN_OWNER.ACTION t
SET t.CODE = 'PROHIBIT_IMPACT'
WHERE t.ID LIKE '01JH70PH9A0N09HZGGF8BP2ZSX' ESCAPE '#';

UPDATE ADMIN_OWNER.ACTION t
SET t.CODE = 'CENSOR'
WHERE t.ID LIKE '01JH70PE3282KVM4TVYJ8KXQ9W' ESCAPE '#';

create table ADMIN_OWNER.API_CATALOG
(
    ID           CHAR(26)         not null
        constraint API_CATALOG_PK
            primary key,
    NAME         VARCHAR2(200)    not null,
    SERVICE_CODE VARCHAR2(20)     not null,
    URI_PATTERN  VARCHAR2(250)    not null,
    METHOD       VARCHAR2(10)     not null,
    STATUS       NUMBER default 1 not null,
    constraint API_CATALOG_PK2
        unique (SERVICE_CODE, URI_PATTERN, METHOD)
)
/

comment on column ADMIN_OWNER.API_CATALOG.NAME is 'Tên gợi nhớ API'
/

comment on column ADMIN_OWNER.API_CATALOG.SERVICE_CODE is 'định danh service'
/

comment on column ADMIN_OWNER.API_CATALOG.URI_PATTERN is 'Uri pattern của API'
/

comment on column ADMIN_OWNER.API_CATALOG.METHOD is 'Method của API'
/

create table ADMIN_OWNER.API_GROUP
(
    ID     CHAR(26)            not null
        constraint API_GROUP_PK
            primary key,
    NAME   VARCHAR2(100)       not null,
    STATUS NUMBER(1) default 1 not null
)
/

comment on column ADMIN_OWNER.API_GROUP.NAME is 'Tên nhóm API'
/

create table ADMIN_OWNER.API_GROUP_ACL
(
    GROUP_ID CHAR(26) not null
        constraint API_GROUP_ACL___FK1
            references ADMIN_OWNER.API_GROUP,
    ACL_ID   CHAR(26) not null
        constraint API_GROUP_ACL___FK2
            references ADMIN_OWNER.OBJECT_ACTION,
    constraint API_GROUP_ACL_PK
        primary key (GROUP_ID, ACL_ID)
)
/

create table ADMIN_OWNER.API_GROUP_CATALOG
(
    GROUP_ID   CHAR(26) not null
        constraint API_GROUP_CATALOG_API_GROUP_ID_FK
            references ADMIN_OWNER.API_GROUP,
    CATALOG_ID CHAR(26) not null
        constraint API_GROUP_CATALOG_API_CATALOG_ID_FK
            references ADMIN_OWNER.API_CATALOG,
    constraint API_GROUP_CATALOG_PK
        primary key (GROUP_ID, CATALOG_ID)
)
/

create table ADMIN_OWNER.API_CATALOG_ACL
(
    CATALOG_ID CHAR(26) not null
        constraint API_CATALOG_ACL_API_CATALOG_ID_FK
            references ADMIN_OWNER.API_CATALOG,
    ACL_ID     CHAR(26) not null
        constraint API_CATALOG_ACL_API_ACL_ID_FK
            references ADMIN_OWNER.OBJECT_ACTION,
    constraint API_CATALOG_ACL_PK
        primary key (CATALOG_ID, ACL_ID)
)
/

UPDATE ADMIN_OWNER.API_CATALOG SET STATUS = 1
         WHERE (URI_PATTERN like '%/api/client%' OR URI_PATTERN like '%/api/users%' OR URI_PATTERN like '%/api/roles%' OR URI_PATTERN like '%/api/groups%')
           AND URI_PATTERN NOT LIKE '%/all';


-- column reordering is not supported SALE_ORDER.REF_ORDER_NO

alter table SALE_OWNER.ISDN_TRANSACTION
    add METADATA CLOB
    /

alter table SALE_OWNER.ISDN_TRANSACTION
    add constraint check_metadata_is_json
        check (METADATA IS JSON)
    /

alter table SALE_OWNER.ISDN_TRANSACTION
    drop column LOG_FILE_URL
/

alter table ADMIN_OWNER.FCM_USER_TOKEN
    modify CLIENT_ID null
/

alter table ADMIN_OWNER.FCM_USER_TOKEN
    modify USER_ID char(26) null
/

UPDATE SALE_OWNER.ISDN_TRANSACTION SET UPLOAD_STATUS = 3 where STEP_STATUS >= 2 AND VALID_FAILED_NUMBER IS NULL OR VALID_FAILED_NUMBER = 0;
UPDATE SALE_OWNER.ISDN_TRANSACTION SET UPLOAD_STATUS = 2 where STEP_STATUS >= 2 AND VALID_FAILED_NUMBER > 0;

ALTER TABLE SALE_OWNER.ORGANIZATION_AIRTIME_TRANSACTION ADD REMAINING_BALANCE NUMBER NULL;
ALTER TABLE SALE_OWNER.ORGANIZATION_AIRTIME_TRANSACTION ADD ISDN VARCHAR(20) NULL;