SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE ADMIN_OWNER.OBJECT_ACTION;
TRUNCATE TABLE ADMIN_OWNER.OBJECT;
TRUNCATE TABLE ADMIN_OWNER.ACTION;
TRUNCATE TABLE ADMIN_OWNER.OAUTH2_REGISTERED_CLIENT;

SET REFERENTIAL_INTEGRITY TRUE;